insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS1', '9 Portage Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS2', '433 Hintze Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS3', '9181 Scoville Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS4', '4119 Doe Crossing Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS5', '82 Atwood Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS6', '282 Kipling Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS7', '46864 Wayridge Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS8', '70 Service Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS9', '958 Dwight Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS10', '1 Debra Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS11', '4 Esch Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS12', '277 Gulseth Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS13', '74499 Jenifer Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS14', '7905 Blue Bill Park Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS15', '742 Superior Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS16', '447 Lakeland Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS17', '2 Wayridge Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS18', '9940 Melby Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS19', '07 Acker Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS20', '61006 8th Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS21', '95 High Crossing Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS22', '737 Mcguire Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS23', '09270 Boyd Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS24', '556 Luster Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS25', '9 Bowman Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS26', '71545 Orin Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS27', '92915 Moose Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS28', '0021 Anzinger Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS29', '4 7th Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS30', '1 Hauk Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS31', '80 Roth Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS32', '721 School Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS33', '1 Doe Crossing Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS34', '270 Blaine Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS35', '47078 Banding Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS36', '564 Donald Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS37', '550 Nobel Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS38', '891 Fieldstone Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS39', '8420 Meadow Valley Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS40', '25503 Mayer Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS41', '99 Calypso Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS42', '587 Florence Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS43', '74 Valley Edge Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS44', '880 Burrows Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS45', '554 Ruskin Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS46', '519 Aberg Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS47', '44 Anzinger Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS48', '98 Drewry Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS49', '5413 Del Sol Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS50', '7662 Crescent Oaks Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS51', '66632 Morning Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS52', '0252 Melby Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS53', '674 Lighthouse Bay Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS54', '63 North Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS55', '2731 Reinke Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS56', '586 Northland Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS57', '546 Hooker Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS58', '9 2nd Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS59', '1047 Gale Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS60', '12282 Cherokee Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS61', '660 Esker Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS62', '9179 Sachs Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS63', '8 Onsgard Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS64', '32 Service Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS65', '557 Tony Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS66', '517 Lawn Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS67', '545 2nd Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS68', '566 Shelley Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS69', '668 Bunker Hill Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS70', '47182 Bartelt Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS71', '9 Blue Bill Park Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS72', '21456 Helena Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS73', '49150 Northfield Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS74', '80973 Lyons Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS75', '74 Pine View Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS76', '0 Sugar Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS77', '28836 Macpherson Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS78', '84 Northview Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS79', '199 Commercial Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS80', '8 Caliangt Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS81', '75998 Melrose Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS82', '872 Acker Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS83', '9 Caliangt Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS84', '583 Schiller Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS85', '4 Artisan Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS86', '297 Sherman Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS87', '41225 Prairieview Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS88', '6 Trailsway Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS89', '2 Buell Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS90', '6594 Sullivan Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS91', '44 Ridgeway Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS92', '1 Vermont Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS93', '5977 Loomis Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS94', '5453 Main Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS95', '98 Duke Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS96', '5797 Manufacturers Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS97', '62 Corscot Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS98', '779 Dottie Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS99', '0 Clemons Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS100', '1137 Sloan Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS101', '2 Main Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS102', '73 Moose Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS103', '5 Loomis Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS104', '81 Towne Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS105', '73668 Menomonie Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS106', '7 Barnett Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS107', '09225 Redwing Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS108', '840 Maryland Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS109', '0 Holy Cross Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS110', '49 Annamark Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS111', '8405 2nd Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS112', '0 Artisan Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS113', '5460 Basil Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS114', '296 2nd Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS115', '6 Russell Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS116', '89404 Drewry Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS117', '7 Brickson Park Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS118', '48 Ludington Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS119', '96151 Shopko Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS120', '7371 Warbler Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS121', '7 Waxwing Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS122', '8813 Fairview Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS123', '330 Saint Paul Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS124', '11 Westridge Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS125', '35 Bartelt Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS126', '7390 8th Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS127', '3292 Harbort Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS128', '68 Darwin Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS129', '443 Merchant Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS130', '5209 Cambridge Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS131', '48 Little Fleur Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS132', '62 Bluejay Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS133', '70689 Katie Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS134', '2 Charing Cross Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS135', '25452 Susan Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS136', '193 Pearson Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS137', '5 Lukken Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS138', '158 Linden Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS139', '24 Dunning Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS140', '230 Talisman Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS141', '02 Burning Wood Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS142', '9 Dottie Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS143', '3 Morning Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS144', '3679 East Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS145', '7 Mifflin Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS146', '0040 Del Mar Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS147', '82 Pierstorff Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS148', '044 Reindahl Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS149', '35154 Westend Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS150', '02447 Talmadge Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS151', '2363 Lakeland Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS152', '105 Northland Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS153', '3 Judy Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS154', '399 Messerschmidt Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS155', '57 Hoffman Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS156', '40621 Schmedeman Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS157', '16943 Little Fleur Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS158', '569 Sunnyside Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS159', '130 Sheridan Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS160', '7 Meadow Ridge Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS161', '8371 Springview Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS162', '7636 Hazelcrest Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS163', '3 Tomscot Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS164', '38 7th Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS165', '1077 Commercial Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS166', '69974 Service Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS167', '98 Petterle Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS168', '70893 Kings Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS169', '88392 Monica Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS170', '39242 Superior Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS171', '8288 Heath Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS172', '548 8th Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS173', '59 Tennessee Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS174', '703 Beilfuss Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS175', '9216 Saint Paul Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS176', '16 Sloan Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS177', '5 Dapin Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS178', '8 Bellgrove Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS179', '1898 Transport Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS180', '81 Quincy Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS181', '4691 Anthes Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS182', '248 Stone Corner Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS183', '666 Walton Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS184', '5386 Algoma Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS185', '45721 Old Gate Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS186', '77 Carioca Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS187', '120 Pine View Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS188', '07324 Ridgeview Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS189', '24676 Graedel Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS190', '6 Dexter Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS191', '47303 Scoville Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS192', '64 Surrey Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS193', '832 Westerfield Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS194', '54 Lillian Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS195', '6 Crownhardt Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS196', '3 High Crossing Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS197', '4 Rutledge Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS198', '7 David Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS199', '1 Maple Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS200', '213 Northridge Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS201', '0 Pierstorff Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS202', '72119 Dottie Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS203', '903 Oneill Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS204', '302 Laurel Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS205', '917 Washington Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS206', '6 Mandrake Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS207', '51384 Elmside Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS208', '3356 Eastwood Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS209', '36 Vermont Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS210', '06914 Cottonwood Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS211', '552 Declaration Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS212', '821 Havey Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS213', '96 Lakewood Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS214', '9502 Summerview Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS215', '47 Springview Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS216', '4 Elmside Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS217', '4316 Sage Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS218', '058 Di Loreto Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS219', '96933 Milwaukee Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS220', '750 Bay Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS221', '09 Muir Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS222', '95 Melby Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS223', '464 Texas Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS224', '95220 Larry Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS225', '0311 Kennedy Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS226', '4 Ludington Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS227', '6558 Grayhawk Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS228', '97 Bluestem Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS229', '36 Clemons Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS230', '060 Darwin Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS231', '624 Mockingbird Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS232', '84 Banding Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS233', '8824 Haas Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS234', '1 Glendale Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS235', '98234 Iowa Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS236', '7 Westerfield Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS237', '06 Shasta Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS238', '60 Green Ridge Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS239', '8 Waxwing Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS240', '1 Vahlen Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS241', '4 Bonner Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS242', '4 Towne Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS243', '207 Drewry Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS244', '41 Lighthouse Bay Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS245', '544 Thompson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS246', '20667 Caliangt Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS247', '70 Hoard Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS248', '449 Doe Crossing Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS249', '717 Vernon Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS250', '7 Lindbergh Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS251', '494 Crownhardt Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS252', '255 Moose Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS253', '66653 Eagan Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS254', '6540 Porter Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS255', '1 Trailsway Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS256', '1703 Hoffman Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS257', '3519 Spohn Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS258', '40 Crescent Oaks Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS259', '4 Johnson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS260', '8382 Coolidge Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS261', '433 Shelley Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS262', '21 Mosinee Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS263', '9 Iowa Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS264', '24 Springs Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS265', '2 Hallows Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS266', '45592 Arkansas Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS267', '2367 Bluestem Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS268', '6 Kennedy Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS269', '4 Dorton Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS270', '7095 Dwight Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS271', '54 Bultman Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS272', '63038 Texas Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS273', '9 Blackbird Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS274', '54027 Muir Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS275', '33799 Artisan Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS276', '73680 Leroy Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS277', '086 Melrose Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS278', '1762 Anderson Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS279', '9427 Cascade Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS280', '97 Pawling Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS281', '4 Basil Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS282', '11 Clyde Gallagher Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS283', '2498 Bashford Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS284', '0 Sherman Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS285', '34 Graedel Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS286', '6599 Debra Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS287', '14 Florence Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS288', '6689 Sycamore Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS289', '52587 Spenser Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS290', '97782 Hooker Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS291', '36 Lakeland Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS292', '980 Stephen Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS293', '0 Mandrake Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS294', '9 Thompson Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS295', '3 Clemons Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS296', '813 Moulton Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS297', '64 Hoepker Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS298', '81 Esker Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS299', '33 Nancy Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS300', '4 Dawn Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS301', '167 Elka Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS302', '588 Carioca Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS303', '1 Drewry Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS304', '570 Shasta Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS305', '75 Oriole Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS306', '06 Ruskin Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS307', '685 Hollow Ridge Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS308', '17224 Hanson Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS309', '1654 Pearson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS310', '7 Hayes Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS311', '992 Harper Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS312', '9 Longview Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS313', '2008 Pine View Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS314', '80 Village Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS315', '08 Anhalt Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS316', '0 Schurz Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS317', '6477 Pleasure Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS318', '06 Everett Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS319', '2 Fremont Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS320', '5 Barby Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS321', '0 Surrey Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS322', '332 Sutherland Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS323', '52 Pankratz Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS324', '254 Sachtjen Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS325', '0204 Butterfield Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS326', '8 Coleman Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS327', '29348 Thompson Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS328', '4070 Nevada Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS329', '30325 Butterfield Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS330', '054 Iowa Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS331', '92 Crest Line Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS332', '7793 Huxley Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS333', '201 Manitowish Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS334', '74380 Larry Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS335', '1334 Forest Dale Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS336', '3741 Pleasure Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS337', '083 Stone Corner Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS338', '8046 Texas Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS339', '9974 Corscot Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS340', '0 Garrison Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS341', '33 Daystar Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS342', '63843 Summit Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS343', '55942 Vera Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS344', '42395 Harper Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS345', '0 Forest Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS346', '84950 Eagan Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS347', '8 Vernon Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS348', '717 Anderson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS349', '30319 Jay Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS350', '1176 Macpherson Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS351', '2 Annamark Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS352', '782 Miller Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS353', '179 Waxwing Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS354', '52868 Lakeland Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS355', '915 Crownhardt Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS356', '22727 Saint Paul Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS357', '9 Kipling Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS358', '419 Crownhardt Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS359', '60068 1st Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS360', '4195 Bay Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS361', '1453 Golf Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS362', '798 Sunnyside Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS363', '99806 Oriole Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS364', '12102 Arizona Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS365', '0522 Forest Dale Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS366', '7808 Spenser Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS367', '74 Clyde Gallagher Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS368', '518 Monument Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS369', '82285 Myrtle Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS370', '798 East Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS371', '148 Dryden Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS372', '15669 Vera Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS373', '36 Butterfield Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS374', '3418 American Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS375', '166 Pond Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS376', '1 Morrow Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS377', '70376 Graceland Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS378', '44939 Sherman Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS379', '4 American Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS380', '8 Bay Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS381', '5 Merchant Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS382', '8568 Parkside Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS383', '8098 Judy Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS384', '4 Warner Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS385', '81 Hintze Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS386', '70 Oakridge Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS387', '5880 Texas Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS388', '7 Burrows Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS389', '5027 Mallory Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS390', '7 Hayes Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS391', '62 Sauthoff Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS392', '2 Cherokee Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS393', '012 Karstens Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS394', '68 Novick Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS395', '7846 Spenser Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS396', '1121 Gerald Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS397', '081 Ridge Oak Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS398', '66895 Eastlawn Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS399', '2273 Lukken Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS400', '36 Randy Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS401', '85 Ilene Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS402', '03 Bultman Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS403', '94776 Clove Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS404', '162 Donald Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS405', '5 Rigney Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS406', '44547 Lakewood Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS407', '41943 Melrose Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS408', '82017 Oakridge Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS409', '1 Saint Paul Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS410', '1 Toban Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS411', '84045 Memorial Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS412', '920 Tony Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS413', '64213 Mayer Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS414', '92 Lotheville Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS415', '39 Southridge Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS416', '713 Butterfield Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS417', '7132 Beilfuss Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS418', '6 Cherokee Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS419', '47 Lukken Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS420', '03433 Lyons Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS421', '134 Harbort Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS422', '009 Tennessee Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS423', '6 New Castle Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS424', '81401 Linden Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS425', '97 Manitowish Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS426', '1 Service Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS427', '523 Killdeer Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS428', '5464 Mifflin Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS429', '804 Ridgeway Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS430', '92643 Macpherson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS431', '4 Londonderry Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS432', '7444 Knutson Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS433', '91298 Bunting Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS434', '72928 Jackson Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS435', '485 Forest Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS436', '82 Lakewood Gardens Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS437', '53932 Grayhawk Place', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS438', '0 Cherokee Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS439', '7 Mcguire Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS440', '80077 Loeprich Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS441', '721 Dottie Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS442', '215 Ramsey Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS443', '7894 Arapahoe Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS444', '8453 Melvin Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS445', '20653 Village Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS446', '64 Old Shore Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS447', '7 Green Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS448', '7 Ridgeview Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS449', '6 Lighthouse Bay Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS450', '022 Hanson Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS451', '6594 Emmet Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS452', '146 Independence Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS453', '4298 Grover Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS454', '2 Novick Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS455', '72682 Mccormick Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS456', '3 Florence Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS457', '3 Mosinee Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS458', '0759 Warrior Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS459', '21 Scofield Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS460', '4128 Morning Way', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS461', '01273 Quincy Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS462', '8 Lighthouse Bay Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS463', '7 Golden Leaf Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS464', '59388 Meadow Valley Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS465', '0497 Iowa Lane', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS466', '342 Ridgeview Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS467', '0 Crowley Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS468', '1 Reindahl Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS469', '2 Heffernan Drive', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS470', '2 Leroy Park', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS471', '143 Moose Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS472', '8847 Golden Leaf Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS473', '6 Vernon Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS474', '33 Elgar Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS475', '2713 Blaine Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS476', '77 Westend Trail', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS477', '9 Hallows Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS478', '7660 Stone Corner Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS479', '3 Maryland Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS480', '109 Division Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS481', '7714 Corscot Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS482', '08 Bunting Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS483', '25 Toban Parkway', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS484', '60873 Miller Alley', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS485', '9 Ridge Oak Junction', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS486', '9 Doe Crossing Avenue', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS487', '25 Judy Crossing', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS488', '5 Delaware Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS489', '644 Meadow Valley Street', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS490', '13886 7th Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS491', '6 Becker Terrace', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS492', '5 Westport Hill', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS493', '53197 Fair Oaks Circle', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS494', '565 Golf Course Court', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS495', '95 Carey Plaza', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS496', '1 Blaine Pass', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS497', '98402 Stang Center', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS498', '48156 Eagle Crest Point', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS499', '5 Pine View Road', 'EPSAndes');
insert into IPS (NOMBRE, LOCALIZACION, ID_EPS) values ('IPS500', '64 Hagan Trail', 'EPSAndes');
