--SI EL USUARIO CON LA IDENTIFICACIÓN NO EXISTE CREO PRIMERO EL USUARIO
INSERT INTO USUARIO (EMAIL, NOMBRE, NUMERO_DOCUMENTO, ROL, TIPO_DOCUMENTO) values (?, ?, ?, ?, ?);
--LUEGO CREO AL MÉDICO 
INSERT INTO MEDICO (ESPECIALIDAD, IDENTIFICACION, NUMERO_REGISTRO_MEDICO) values (?, ?, ?);
--LUEGO ASOCIO EL MEDICO A LA IPS EN LA QUE ME DICE QUE TRABAJA O LAS QUE ME DICE, ESTA(S) TIENE(N) QUE EXISTIR
INSERT INTO TRABAJAN (ID_MEDICO, ID_IPS) values (?, ?);

