--SI EL USUARIO CON LA IDENTIFICACIÓN NO EXISTE CREO PRIMERO EL USUARIO
INSERT INTO USUARIO (EMAIL, NOMBRE, NUMERO_DOCUMENTO, ROL, TIPO_DOCUMENTO) values (?, ?, ?, ?, ?);
--LUEGO CREO AL AFILIADO 
INSERT INTO AFILIADO(EPS, IDENTIFICACION, FECHA_NACIMIENTO) values (?, ?, ?);


