--SI EL SERVICIO VA A SER PRESTADO POR PRIMERA VEZ, LO CREO
INSERT INTO SERVICIO (NOMBRE, TIPO) values (?, ?);
--LUEGO CREO LA RELACIÓN ENTRE EL SERVICIO, LA IPS, SU HORARIO Y CAPACIDAD
INSERT INTO PRESTAN (DURACION, HORAINICIO, DIA, ID_SERVICIO, ID_IPS, CAPACIDAD) values (?,?,?,?,?,?);

