--RF10
--Registro al organizador
--Saco la cantidad de servicios en ese rango
SELECT SUM(CAPACIDAD) FROM PRESTAN tp  WHERE ID_SERVICIO=? AND TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND CANCELADA=0;
--Registro un afiliado que es la campaña
INSERT INTO USUARIO (EMAIL, NOMBRE, NUMERO_DOCUMENTO, ROL, TIPO_DOCUMENTO) values (?, ?, ?, ?, ?);
INSERT INTO AFILIADO (EPS, IDENTIFICACION, FECHA_NACIMIENTO) values (?, ?, ?);
--Saco la información de los servicios en ese rango
SELECT * FROM PRESTAN tp  WHERE ID_SERVICIO=? AND TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND CANCELADA=0;
--Saco las reservas con base a la información previa
INSERT INTO CITA (CUMPLIDA, ID_ORDEN , FECHA, ID_SERVICIO, ID_AFILIADO, ID_RECEPCIONISTA, HORA) values (?,?, ?, ?, ?, ?, ?);
UPDATE PRESTAN SET CAPACIDAD=? WHERE DIA=? AND ID_SERVICIO=? AND ID_IPS=? AND HORAINICIO=?;
--Registro la campania
INSERT INTO CAMPANIA (NOMBRE,FECHAFIN,FECHAINICIO,ID_ORGANIZADOR) VALUES (?,?,?,?);
--Asocio los servicios a la campania
INSERT INTO RESERVACAMPANIA (CAPACIDADF,ID_SERVICIO,ID_CAMPANIA,CAPACIDADINI,FECHAINI,FECHAFIN) VALUES (?,?,?,?,?,?);

--RF11
--Pido el usuario de la campania
SELECT * FROM USUARIO WHERE NOMBRE = ?;
--Pido la iformación de SERVICIOCAMPANIA para devolver los cupos
SELECT * FROM RESERVACAMPANIA WHERE ID_SERVICIO=? AND ID_CAMPANIA=?;
--Pido la información de los servicos en rango para liberar cupos
SELECT * FROM PRESTAN tp  WHERE ID_SERVICIO=? AND TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND CANCELADA=0;
--Actualizo la capacidad para liberar cupos
UPDATE PRESTAN SET CAPACIDAD=? WHERE DIA=? AND ID_SERVICIO=?;
--Elimino las citas sacadas a nombre de la campania
DELETE FROM CITA WHERE ID_SERVICIO=? AND ID_AFILIADO =?;
--Elimino al servicio de la campania
DELETE FROM RESERVACAMPANIA WHERE ID_SERVICIO=? AND ID_CAMPANIA=?;

--RF12
--Cambio la habilidad del servicio a 1 
UPDATE PRESTAN SET CANCELADA=? WHERE (TO_DATE(DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS')) AND ID_SERVICIO=? AND ID_IPS=?;
--Saco las citas por IPS y servicio
SELECT tc.ID_ORDEN, tc.FECHA, tc.HORA, tc.ID_AFILIADO FROM CITA tc, PRESTAN tp, RECEPCIONISTA_IPS tr WHERE tp.ID_SERVICIO=tc.ID_SERVICIO AND tp.ID_SERVICIO=? AND tp.ID_IPS=? AND tp.ID_IPS=tc.ID_RECEPCIONISTA AND TO_DATE(tc.FECHA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS');
--Saco la información del servicio en rango
SELECT * FROM PRESTAN tp  WHERE ID_SERVICIO=? AND TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND CANCELADA=0;
--Saco la capacidad de todos los servicios en ese rango
SELECT SUM(CAPACIDAD) FROM PRESTAN tp  WHERE ID_SERVICIO=? AND TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND CANCELADA=0;
--Registro la nueva cita si puedo y debo
INSERT INTO USUARIO (EMAIL, NOMBRE, NUMERO_DOCUMENTO, ROL, TIPO_DOCUMENTO) values (?, ?, ?, ?, ?);
INSERT INTO AFILIADO (EPS, IDENTIFICACION, FECHA_NACIMIENTO) values (?, ?, ?);
--Elimino la cita de la IPS donde estaba
DELETE FROM CITA WHERE ID_SERVICIO=? AND ID_AFILIADO =? AND ID_RECEPCIONISTA=?;

--RF13
--Cambio la habilidad del servicio a 0
UPDATE PRESTAN SET CANCELADA=? WHERE (TO_DATE(DIA,'DD-MM-YY HH24:MI:SS') BETWEEN TO_DATE(?,'DD-MM-YY HH24:MI:SS') AND TO_DATE(?,'DD-MM-YY HH24:MI:SS')) AND ID_SERVICIO=? AND ID_IPS=?;

--RFC6
--Saco las semanas donde mas se demandó el servicio
SELECT SUM(CAPACIDADMAX-CAPACIDAD) AS DIFERENCIA, to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), ?)) SEMANA FROM PRESTAN tp WHERE ID_SERVICIO=?
    GROUP BY to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), ?))
    ORDER BY SUM(CAPACIDADMAX-CAPACIDAD) DESC FETCH NEXT 5 ROWS ONLY;
--Saco las semanas donde menos se demandó el servicio
SELECT SUM(CAPACIDADMAX-CAPACIDAD) AS DIFERENCIA, to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), ?)) SEMANA FROM PRESTAN tp WHERE ID_SERVICIO=?
    GROUP BY to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), ?))
    ORDER BY SUM(CAPACIDADMAX-CAPACIDAD) ASC FETCH NEXT 5 ROWS ONLY;
--Saco las semanas donde hubo mayor actividad
SELECT COUNT (*) CUMPLIDAS,to_number(to_char(TO_DATE(tc.FECHA,'DD-MM-YY HH24:MI:SS'), ?)) FECHA FROM CITA tc 
    WHERE tc.CUMPLIDA=1 AND tc.ID_SERVICIO=? GROUP BY to_number(to_char(TO_DATE(tc.FECHA,'DD-MM-YY HH24:MI:SS'),?))
	ORDER BY COUNT(*) DESC
	FETCH NEXT 5 ROWS ONLY;

--RFC7
SELECT aux.AFILIADO,aux.TIPOS,aux.SERVICIOS FROM(
    SELECT tc.ID_AFILIADO AFILIADO, COUNT (DISTINCT ts.TIPO) TIPOS, COUNT (tc.ID_SERVICIO) SERVICIOS FROM CITA tc, SERVICIO ts 
	WHERE ts.NOMBRE=tc.ID_SERVICIO AND to_number(to_char(TO_DATE(tc.FECHA,'DD-MM-YY HH24:MI:SS'), 'YY'))=to_number(to_char(CURRENT_DATE, 'YY'))-1
	GROUP BY tc.ID_AFILIADO,ts.TIPO, tc.ID_SERVICIO) aux
WHERE aux.TIPOS>2 AND aux.SERVICIOS>12;

--RFC8
SELECT DISTINCT ID_SERVICIO FROM 
    (SELECT ID_SERVICIO,SUM(CAPACIDADMAX-CAPACIDAD) DIFERENCIA FROM PRESTAN tp 
     WHERE to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), 'YY'))=to_number(to_char(CURRENT_DATE, 'YY'))-1 
     GROUP BY ID_SERVICIO,to_number(to_char(TO_DATE(tp.DIA,'DD-MM-YY HH24:MI:SS'), 'WW'))) 
WHERE DIFERENCIA<3;