--Se crea el secuenciador, las restricciones y las tablas en un solo archivo para facilidad de
--lectura y creación. Todo está ordenado para no tener errores en la creación.

-- Creación del secuenciador
create sequence epsandes_sequence;

-- Creación de la tabla USUARIO y especificación de sus restricciones
CREATE TABLE ROL(
NOMBRE VARCHAR(255),
CONSTRAINT PK_ROL PRIMARY KEY(NOMBRE) ENABLE
);

ALTER TABLE ROL
ADD CONSTRAINT CONST_ROL CHECK(NOMBRE IN
(
    'Afiliado',
    'RecepcionistaIPS',
    'Medico',
    'AdminDatosEPS',
    'GerenteEPS',
    'OrganizadorCampania'
))ENABLE;

CREATE TABLE USUARIO(
    EMAIL VARCHAR(255) NOT NULL  UNIQUE,
    NOMBRE VARCHAR(255) NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(255),
    ROL VARCHAR(255) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(NUMERO_DOCUMENTO) ENABLE,
    CONSTRAINT FK_ROL FOREIGN KEY(ROL) REFERENCES ROL(NOMBRE) ENABLE
); 

ALTER TABLE USUARIO
ADD CONSTRAINT CONS_TIPO_DOCUMENTO CHECK(TIPO_DOCUMENTO IN
(
    'C.C',
    'T.I',
    'C.E',
    'R.C',
    'PASAPORTE'
)) ENABLE;

-- Creación de la tabla EPS y especificación de sus restricciones
CREATE TABLE EPS(
    NOMBRE VARCHAR(255),
    CONSTRAINT PK_EPS PRIMARY KEY(NOMBRE) ENABLE
);

-- Creación de la tabla IPS y especificación de sus restricciones
CREATE TABLE IPS(
    NOMBRE VARCHAR(255),
    LOCALIZACION VARCHAR(255) NOT NULL,
    ID_EPS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_IPS PRIMARY KEY(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_EPS_IPS FOREIGN KEY(ID_EPS) REFERENCES EPS(NOMBRE)ENABLE
);

--Creación de la tabla ORGANIZADORCAMPANIA y especificación de sus restricciones.
CREATE TABLE ORGANIZADORCAMPANIA(
    IDENTIFICACION VARCHAR(255),
    CONSTRAINT PK_ORGANIZADOR PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_IDENTIFICACION_ORGANIZADORC FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE
);

-- Creación de la tabla MEDICO y especificación de sus restricciones
CREATE TABLE MEDICO(
    IDENTIFICACION VARCHAR(255),
    ESPECIALIDAD VARCHAR(255) NOT NULL,
    NUMERO_REGISTRO_MEDICO VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT PK_MEDICO PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_IDENTIFICACION_MEDICO FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE
);

-- Creación de la tabla RECEPCIONISTA_IPS y especificación de sus restricciones
CREATE TABLE RECEPCIONISTA_IPS(
    IDENTIFICACION VARCHAR(255),
    ID_IPS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_RECEPCIONISTA_IPS PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_IDENTIFICACION_RECEPCION FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE,
    CONSTRAINT FK_ID_IPS FOREIGN KEY (ID_IPS) REFERENCES IPS(NOMBRE) ENABLE
);


-- Creación de la tabla GERENTE_EPS y especificación de sus restricciones
CREATE TABLE GERENTE_EPS(
    IDENTIFICACION VARCHAR(255),
    ID_EPS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GERENTE PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_IDENTIFICACION_GERENTE FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE,
    CONSTRAINT FK_ID_EPS_GERENTE FOREIGN KEY(ID_EPS) REFERENCES EPS(NOMBRE) ENABLE
);


-- Creación de la tabla ADMINDATOSEPS y especificación de sus restricciones
CREATE TABLE ADMINDATOSEPS(
    IDENTIFICACION VARCHAR(255),
    ID_EPS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ADMIN_DATOS_EPS PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_ID_USUARIO_ADMIN FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE,
    CONSTRAINT FK_ID_EPS_ADMIN FOREIGN KEY(ID_EPS) REFERENCES EPS(NOMBRE) ENABLE
);


-- Creación de la tabla AFILIADO y especificación de sus restricciones
CREATE TABLE AFILIADO(
    IDENTIFICACION VARCHAR(255),
    FECHA_NACIMIENTO VARCHAR(255)NOT NULL,
    EPS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_AFILIADO PRIMARY KEY(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_ID_USUARIO_AFILIADO FOREIGN KEY(IDENTIFICACION) REFERENCES USUARIO(NUMERO_DOCUMENTO) ENABLE,
    CONSTRAINT FK_EPS_AFILIADO FOREIGN KEY(EPS) REFERENCES EPS(NOMBRE) ENABLE
);


--Creación de la tabla CAMPANIA  y especificación de sus restricciones.
CREATE TABLE CAMPANIA(
    NOMBRE VARCHAR(255),
    FECHAFIN VARCHAR(255) NOT NULL,
    FECHAINICIO VARCHAR(255) NOT NULL,
    ID_ORGANIZADOR VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CAMPANIA PRIMARY KEY(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_ORGANIZADOR FOREIGN KEY(ID_ORGANIZADOR) REFERENCES ORGANIZADORCAMPANIA(IDENTIFICACION) ENABLE
);

-- Creación de la tabla SERVICIO y especificación de sus restricciones
CREATE TABLE SERVICIO(
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    CONSTRAINT PK_SERVICIO PRIMARY KEY (NOMBRE) ENABLE
);

ALTER TABLE SERVICIO
ADD CONSTRAINT CONS_TIPO CHECK(TIPO IN(
    'Consulta con medico',
    'Consulta de urgencias',
    'Remision con un especialista',
    'Consulta de control',
    'Examen diagnostico',
    'Terapia',
    'Procedimiento medico especializado',
    'Hospitalizacion'
))ENABLE;


-- Creación de la tabla OFRECEN y especificación de sus restricciones
CREATE TABLE OFRECEN
(
    ID_MEDICO VARCHAR(255),
    ID_SERVICIO VARCHAR(255),
    CONSTRAINT PK_OFRECEN PRIMARY KEY(ID_MEDICO,ID_SERVICIO) ENABLE,
    CONSTRAINT FK_ID_MEDICO FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDENTIFICACION)ENABLE,
    CONSTRAINT FK_ID_SERVICIO FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(NOMBRE) ENABLE
);


-- Creación de la tabla PRESTAN y especificación de sus restricciones
CREATE TABLE PRESTAN(
    DURACION VARCHAR(255) NOT NULL,
    HORAINICIO VARCHAR(255),
    DIA VARCHAR(255),
    ID_SERVICIO VARCHAR(255),
    ID_IPS VARCHAR(255),
    CAPACIDAD NUMBER NOT NULL,
    CANCELADA NUMBER NOT NULL,
    CAPACIDADMAX NUMBER NOT NULL,
    CONSTRAINT PK_PRESTAN PRIMARY KEY(ID_IPS,ID_SERVICIO,DIA,HORAINICIO) ENABLE,
    CONSTRAINT FK_ID_IPS_PRESTAN FOREIGN KEY(ID_IPS) REFERENCES IPS(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_SERVICIO_PRESTAN FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(NOMBRE) ENABLE
);

ALTER TABLE PRESTAN
ADD CONSTRAINT CONS_CAPACIDAD CHECK (CAPACIDAD>=0)
ENABLE;
ALTER TABLE PRESTAN
ADD CONSTRAINT CONS_CAPACIDADMAX CHECK (CAPACIDADMAX>0)
ENABLE;

-- Creación de la tabla ReservaCampania y especificación de sus restricciones
CREATE TABLE RESERVACAMPANIA(
    CAPACIDADF NUMBER NOT NULL,
    ID_SERVICIO VARCHAR(255),
    ID_CAMPANIA VARCHAR(255),
    CAPACIDADINI NUMBER NOT NULL,
    CONSTRAINT PK_RESERVACA PRIMARY KEY(ID_CAMPANIA,ID_SERVICIO) ENABLE,
    CONSTRAINT FK_ID_RESERVA_CAMPANIA FOREIGN KEY(ID_CAMPANIA) REFERENCES CAMPANIA(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_SERVICIO_RESERVAC FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(NOMBRE) ENABLE
);
ALTER TABLE RESERVACAMPANIA
ADD CONSTRAINT CONS_CAPACIDADCI CHECK (CAPACIDADINI>0)
ENABLE;
ALTER TABLE RESERVACAMPANIA
ADD CONSTRAINT CONS_CAPACIDADCF CHECK (CAPACIDADF>=0)
ENABLE;

-- Creación de la tabla ORDEN y especificación de sus restricciones
CREATE TABLE ORDEN(
    ID_AFILIADO VARCHAR(255) NOT NULL,
    ID_MEDICO VARCHAR(255) NOT NULL,
    ID NUMBER,
    NOM_SERVICIO VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ORDEN PRIMARY KEY (ID) ENABLE,
    CONSTRAINT FK_NOMBRE_SERVICIO_ORDEN FOREIGN KEY (NOM_SERVICIO) REFERENCES SERVICIO(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_AFILIADO_ORDEN FOREIGN KEY (ID_AFILIADO) REFERENCES AFILIADO(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_ID_MEDICO_ORDEN FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(IDENTIFICACION) ENABLE
);
-- Creación de la tabla CITA y especificación de sus restricciones
CREATE TABLE CITA(
    CUMPLIDA NUMBER NOT NULL,
    ID_ORDEN NUMBER,
    FECHA VARCHAR(255) NOT NULL,
    HORA VARCHAR(255) NOT NULL,
    ID_SERVICIO VARCHAR(255) NOT NULL,
    ID_AFILIADO VARCHAR(255) NOT NULL,
    ID_RECEPCIONISTA VARCHAR(255),
    CONSTRAINT PK_CITA PRIMARY KEY(ID_ORDEN) ENABLE,
    CONSTRAINT FK_ID_ORDEN_CITA FOREIGN KEY(ID_ORDEN) REFERENCES ORDEN(ID) ENABLE,
    CONSTRAINT FK_ID_SERVICIO_CITA FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(NOMBRE) ENABLE,
    CONSTRAINT FK_ID_AFILIADO_CITA FOREIGN KEY (ID_AFILIADO) REFERENCES AFILIADO(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_ID_RECEPCIONISTA_CITA FOREIGN KEY(ID_RECEPCIONISTA) REFERENCES RECEPCIONISTA_IPS(IDENTIFICACION) ENABLE	
);

-- Creación de la tabla TRABAJAN y especificación de sus restricciones
CREATE TABLE TRABAJAN(
    ID_MEDICO VARCHAR(255),
    ID_IPS VARCHAR(255),
    CONSTRAINT PK_TRABAJAN PRIMARY KEY (ID_MEDICO,ID_IPS) ENABLE,
    CONSTRAINT FK_ID_MEDICO_TRABAJAN FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(IDENTIFICACION) ENABLE,
    CONSTRAINT FK_ID_IPS_TRABAJAN FOREIGN KEY (ID_IPS) REFERENCES IPS(NOMBRE) ENABLE
);

COMMIT;