-- Eliminar todas las tablas de la base de datos
DROP TABLE ADMINDATOSEPS CASCADE CONSTRAINTS;
DROP TABLE ORDEN CASCADE CONSTRAINTS;
DROP TABLE CITA CASCADE CONSTRAINTS;
DROP TABLE GERENTE_EPS CASCADE CONSTRAINTS;
DROP TABLE OFRECEN CASCADE CONSTRAINTS;
DROP TABLE PRESTAN CASCADE CONSTRAINTS;
DROP TABLE RECEPCIONISTA_IPS CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE TRABAJAN CASCADE CONSTRAINTS;
DROP TABLE AFILIADO CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;
DROP TABLE IPS CASCADE CONSTRAINTS;
DROP TABLE EPS CASCADE CONSTRAINTS;
COMMIT;

-- Eliminar el contenido de todas las tablas de la base de datos
DELETE FROM ADMINDATOSEPS;
DELETE FROM ORDEN;
DELETE FROM CITA;
DELETE FROM GERENTEEPS;
DELETE FROM OFRECEN;
DELETE FROM PRESTAN;
DELETE FROM RECEPCIONISTAIPS;
DELETE FROM SERVICIO;
DELETE FROM TRABAJAN;
DELETE FROM AFILIADO;
DELETE FROM MEDICO;
DELETE FROM USUARIO;
DELETE FROM ROL;
DELETE FROM IPS;
DELETE FROM EPS;
COMMIT;